# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"H\n\x1fStandardVocalSeparationResponse\x12\x0e\n\x06vocals\x18\x01 \x01(\x0c\x12\x15\n\raccompaniment\x18\x02 \x01(\x0c\"\\\n\x1eStandardBandSeparationResponse\x12\x0c\n\x04\x62\x61ss\x18\x01 \x01(\x0c\x12\r\n\x05\x64rums\x18\x02 \x01(\x0c\x12\r\n\x05other\x18\x03 \x01(\x0c\x12\x0e\n\x06vocals\x18\x04 \x01(\x0c\"<\n\x18StandardTransposeRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x11\n\tsemitones\x18\x02 \x01(\x02\"\x1d\n\x0c\x41udioRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\x1e\n\rAudioResponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\x1c\n\x0cMidiResponse\x12\x0c\n\x04midi\x18\x01 \x01(\x0c\"$\n\x12HalfPlusTwoRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\x02\"&\n\x13HalfPlusTwoResponse\x12\x0f\n\x07outputs\x18\x01 \x03(\x02\"\x1e\n\x0c\x41\x64\x64\x65rRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\x02\"\x1f\n\rAdderResponse\x12\x0e\n\x06output\x18\x01 \x01(\x02\"0\n\x10StandardAudioTag\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"?\n\x1cStandardAudioTaggingResponse\x12\x1f\n\x04tags\x18\x01 \x03(\x0b\x32\x11.StandardAudioTag2\xef\x04\n\x02\x46n\x12?\n\x10LibrosaTranspose\x12\x19.StandardTransposeRequest\x1a\x0e.AudioResponse\"\x00\x12@\n\x1eOnsetsAndFramesPianoTranscribe\x12\r.AudioRequest\x1a\r.MidiResponse\"\x00\x12?\n\x1dOnsetsAndFramesDrumTranscribe\x12\r.AudioRequest\x1a\r.MidiResponse\"\x00\x12J\n\x18PannAudioTaggingResnet38\x12\r.AudioRequest\x1a\x1d.StandardAudioTaggingResponse\"\x00\x12N\n\x19WavUNetM4SourceSeparation\x12\r.AudioRequest\x1a .StandardVocalSeparationResponse\"\x00\x12T\n\x1fWavUNetM5HighSrSourceSeparation\x12\r.AudioRequest\x1a .StandardVocalSeparationResponse\"\x00\x12M\n\x19WavUNetM6SourceSeparation\x12\r.AudioRequest\x1a\x1f.StandardBandSeparationResponse\"\x00\x12:\n\x0bHalfPlusTwo\x12\x13.HalfPlusTwoRequest\x1a\x14.HalfPlusTwoResponse\"\x00\x12(\n\x05\x41\x64\x64\x65r\x12\r.AdderRequest\x1a\x0e.AdderResponse\"\x00\x62\x06proto3'
)




_STANDARDVOCALSEPARATIONRESPONSE = _descriptor.Descriptor(
  name='StandardVocalSeparationResponse',
  full_name='StandardVocalSeparationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vocals', full_name='StandardVocalSeparationResponse.vocals', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accompaniment', full_name='StandardVocalSeparationResponse.accompaniment', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=89,
)


_STANDARDBANDSEPARATIONRESPONSE = _descriptor.Descriptor(
  name='StandardBandSeparationResponse',
  full_name='StandardBandSeparationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bass', full_name='StandardBandSeparationResponse.bass', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drums', full_name='StandardBandSeparationResponse.drums', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='other', full_name='StandardBandSeparationResponse.other', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vocals', full_name='StandardBandSeparationResponse.vocals', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=183,
)


_STANDARDTRANSPOSEREQUEST = _descriptor.Descriptor(
  name='StandardTransposeRequest',
  full_name='StandardTransposeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='StandardTransposeRequest.audio', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='semitones', full_name='StandardTransposeRequest.semitones', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=245,
)


_AUDIOREQUEST = _descriptor.Descriptor(
  name='AudioRequest',
  full_name='AudioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='AudioRequest.audio', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=276,
)


_AUDIORESPONSE = _descriptor.Descriptor(
  name='AudioResponse',
  full_name='AudioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='AudioResponse.audio', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=308,
)


_MIDIRESPONSE = _descriptor.Descriptor(
  name='MidiResponse',
  full_name='MidiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='midi', full_name='MidiResponse.midi', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=338,
)


_HALFPLUSTWOREQUEST = _descriptor.Descriptor(
  name='HalfPlusTwoRequest',
  full_name='HalfPlusTwoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='HalfPlusTwoRequest.inputs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=376,
)


_HALFPLUSTWORESPONSE = _descriptor.Descriptor(
  name='HalfPlusTwoResponse',
  full_name='HalfPlusTwoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputs', full_name='HalfPlusTwoResponse.outputs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=416,
)


_ADDERREQUEST = _descriptor.Descriptor(
  name='AdderRequest',
  full_name='AdderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='AdderRequest.inputs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=448,
)


_ADDERRESPONSE = _descriptor.Descriptor(
  name='AdderResponse',
  full_name='AdderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='AdderResponse.output', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=481,
)


_STANDARDAUDIOTAG = _descriptor.Descriptor(
  name='StandardAudioTag',
  full_name='StandardAudioTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='StandardAudioTag.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='StandardAudioTag.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=531,
)


_STANDARDAUDIOTAGGINGRESPONSE = _descriptor.Descriptor(
  name='StandardAudioTaggingResponse',
  full_name='StandardAudioTaggingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tags', full_name='StandardAudioTaggingResponse.tags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=596,
)

_STANDARDAUDIOTAGGINGRESPONSE.fields_by_name['tags'].message_type = _STANDARDAUDIOTAG
DESCRIPTOR.message_types_by_name['StandardVocalSeparationResponse'] = _STANDARDVOCALSEPARATIONRESPONSE
DESCRIPTOR.message_types_by_name['StandardBandSeparationResponse'] = _STANDARDBANDSEPARATIONRESPONSE
DESCRIPTOR.message_types_by_name['StandardTransposeRequest'] = _STANDARDTRANSPOSEREQUEST
DESCRIPTOR.message_types_by_name['AudioRequest'] = _AUDIOREQUEST
DESCRIPTOR.message_types_by_name['AudioResponse'] = _AUDIORESPONSE
DESCRIPTOR.message_types_by_name['MidiResponse'] = _MIDIRESPONSE
DESCRIPTOR.message_types_by_name['HalfPlusTwoRequest'] = _HALFPLUSTWOREQUEST
DESCRIPTOR.message_types_by_name['HalfPlusTwoResponse'] = _HALFPLUSTWORESPONSE
DESCRIPTOR.message_types_by_name['AdderRequest'] = _ADDERREQUEST
DESCRIPTOR.message_types_by_name['AdderResponse'] = _ADDERRESPONSE
DESCRIPTOR.message_types_by_name['StandardAudioTag'] = _STANDARDAUDIOTAG
DESCRIPTOR.message_types_by_name['StandardAudioTaggingResponse'] = _STANDARDAUDIOTAGGINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StandardVocalSeparationResponse = _reflection.GeneratedProtocolMessageType('StandardVocalSeparationResponse', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDVOCALSEPARATIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StandardVocalSeparationResponse)
  })
_sym_db.RegisterMessage(StandardVocalSeparationResponse)

StandardBandSeparationResponse = _reflection.GeneratedProtocolMessageType('StandardBandSeparationResponse', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDBANDSEPARATIONRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StandardBandSeparationResponse)
  })
_sym_db.RegisterMessage(StandardBandSeparationResponse)

StandardTransposeRequest = _reflection.GeneratedProtocolMessageType('StandardTransposeRequest', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDTRANSPOSEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StandardTransposeRequest)
  })
_sym_db.RegisterMessage(StandardTransposeRequest)

AudioRequest = _reflection.GeneratedProtocolMessageType('AudioRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:AudioRequest)
  })
_sym_db.RegisterMessage(AudioRequest)

AudioResponse = _reflection.GeneratedProtocolMessageType('AudioResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUDIORESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:AudioResponse)
  })
_sym_db.RegisterMessage(AudioResponse)

MidiResponse = _reflection.GeneratedProtocolMessageType('MidiResponse', (_message.Message,), {
  'DESCRIPTOR' : _MIDIRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:MidiResponse)
  })
_sym_db.RegisterMessage(MidiResponse)

HalfPlusTwoRequest = _reflection.GeneratedProtocolMessageType('HalfPlusTwoRequest', (_message.Message,), {
  'DESCRIPTOR' : _HALFPLUSTWOREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:HalfPlusTwoRequest)
  })
_sym_db.RegisterMessage(HalfPlusTwoRequest)

HalfPlusTwoResponse = _reflection.GeneratedProtocolMessageType('HalfPlusTwoResponse', (_message.Message,), {
  'DESCRIPTOR' : _HALFPLUSTWORESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:HalfPlusTwoResponse)
  })
_sym_db.RegisterMessage(HalfPlusTwoResponse)

AdderRequest = _reflection.GeneratedProtocolMessageType('AdderRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDERREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:AdderRequest)
  })
_sym_db.RegisterMessage(AdderRequest)

AdderResponse = _reflection.GeneratedProtocolMessageType('AdderResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDERRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:AdderResponse)
  })
_sym_db.RegisterMessage(AdderResponse)

StandardAudioTag = _reflection.GeneratedProtocolMessageType('StandardAudioTag', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDAUDIOTAG,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StandardAudioTag)
  })
_sym_db.RegisterMessage(StandardAudioTag)

StandardAudioTaggingResponse = _reflection.GeneratedProtocolMessageType('StandardAudioTaggingResponse', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDAUDIOTAGGINGRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:StandardAudioTaggingResponse)
  })
_sym_db.RegisterMessage(StandardAudioTaggingResponse)



_FN = _descriptor.ServiceDescriptor(
  name='Fn',
  full_name='Fn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=599,
  serialized_end=1222,
  methods=[
  _descriptor.MethodDescriptor(
    name='LibrosaTranspose',
    full_name='Fn.LibrosaTranspose',
    index=0,
    containing_service=None,
    input_type=_STANDARDTRANSPOSEREQUEST,
    output_type=_AUDIORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OnsetsAndFramesPianoTranscribe',
    full_name='Fn.OnsetsAndFramesPianoTranscribe',
    index=1,
    containing_service=None,
    input_type=_AUDIOREQUEST,
    output_type=_MIDIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OnsetsAndFramesDrumTranscribe',
    full_name='Fn.OnsetsAndFramesDrumTranscribe',
    index=2,
    containing_service=None,
    input_type=_AUDIOREQUEST,
    output_type=_MIDIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PannAudioTaggingResnet38',
    full_name='Fn.PannAudioTaggingResnet38',
    index=3,
    containing_service=None,
    input_type=_AUDIOREQUEST,
    output_type=_STANDARDAUDIOTAGGINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WavUNetM4SourceSeparation',
    full_name='Fn.WavUNetM4SourceSeparation',
    index=4,
    containing_service=None,
    input_type=_AUDIOREQUEST,
    output_type=_STANDARDVOCALSEPARATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WavUNetM5HighSrSourceSeparation',
    full_name='Fn.WavUNetM5HighSrSourceSeparation',
    index=5,
    containing_service=None,
    input_type=_AUDIOREQUEST,
    output_type=_STANDARDVOCALSEPARATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WavUNetM6SourceSeparation',
    full_name='Fn.WavUNetM6SourceSeparation',
    index=6,
    containing_service=None,
    input_type=_AUDIOREQUEST,
    output_type=_STANDARDBANDSEPARATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HalfPlusTwo',
    full_name='Fn.HalfPlusTwo',
    index=7,
    containing_service=None,
    input_type=_HALFPLUSTWOREQUEST,
    output_type=_HALFPLUSTWORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Adder',
    full_name='Fn.Adder',
    index=8,
    containing_service=None,
    input_type=_ADDERREQUEST,
    output_type=_ADDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FN)

DESCRIPTOR.services_by_name['Fn'] = _FN

# @@protoc_insertion_point(module_scope)
